version: '3.4'

services:
  webui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  kycservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  apigetway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

